/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsPlaygroundRouteImport } from './routes/components-playground'
import { Route as IndexRouteImport } from './routes/index'

const ComponentsPlaygroundRoute = ComponentsPlaygroundRouteImport.update({
  id: '/components-playground',
  path: '/components-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components-playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components-playground'
  id: '__root__' | '/' | '/components-playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsPlaygroundRoute: typeof ComponentsPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components-playground': {
      id: '/components-playground'
      path: '/components-playground'
      fullPath: '/components-playground'
      preLoaderRoute: typeof ComponentsPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsPlaygroundRoute: ComponentsPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
